#!/bin/sh
#
# %CopyrightBegin%
# 
# Copyright Ericsson AB 1996-2016. All Rights Reserved.
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# 
# %CopyrightEnd%
#

# Replaces the Erlang "erl" script for the CloudI example release.

SCRIPT_PATH=`dirname $0`
ROOTDIR=`cd $SCRIPT_PATH/../.. && pwd`
START_ERL_DATA="$ROOTDIR/releases/start_erl.data"
ERLANG_ERTS_VERSION=`cat $START_ERL_DATA | awk '{print $1}'`
RELEASE_VERSION=`cat $START_ERL_DATA | awk '{print $2}'`
BINDIR="$ROOTDIR/erts-$ERLANG_ERTS_VERSION/bin"
EMU=beam
PROGNAME=erl
export EMU
export ROOTDIR
export BINDIR
export PROGNAME
RELEASEDIR="$ROOTDIR/releases/$RELEASE_VERSION"
exec "$BINDIR/erlexec" -boot "$RELEASEDIR/start_clean" ${1+"$@"}

