language: erlang
script: rebar compile && rebar skip_deps=true eunit
otp_release:
  - 17.1
  - 17.0
  - R16B03-1
  - R16B03
  - R16B02
  - R16B01
  - R16B
  - R15B02
  - R15B01
  - R15B
  - R14B04
  - R14B03
  - R14B02
