#!/bin/sh

# flags common for development

# g++
PEDANTIC_DISABLE=""
# clang++ is angered by Python2 C register use due to C++17
#PEDANTIC_DISABLE="$PEDANTIC_DISABLE -Wno-deprecated-register"

# gcc >= 9.3.0 or clang >= 10.0.0 are best when checking pedantic errors
#PEDANTIC="-pedantic-errors $PEDANTIC_DISABLE"
PEDANTIC=""

# Both AM_CXXFLAGS and CXXFLAGS appear in the command-line that the makefiles
# create and that is normal (the options below get replicated).
make CXXFLAGS="-Wall -Wextra -Werror -O0 -g $PEDANTIC" $*
exit $?
